# # https://github.com/rust-lang/rustfmt/blob/master/Configurations.md

edition = "2018"
max_width = 120
merge_derives = true
use_field_init_shorthand = true
use_try_shorthand = true

imports_layout = "HorizontalVertical"
imports_granularity = "Module"
overflow_delimited_expr = true
reorder_impl_items = true
version = "Two"
